version: '3'
services:
  #####################
  # NGINX
  #####################
  nginx:
    image: nginx
    container_name: notes_nginx
    build: ./nginx
    restart: always
    links:
      - notes_api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/dist/:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/nginx/:/var/logs/nginx
    depends_on:
      - notes_api
    networks:
      - notes_network
  ####################
  # NODE
  ####################
  notes_api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes_api
    image: notes_api
    links:
      - postgresDB
    volumes:
      - ./:/opt/notes_api
      - notes_data:/opt/notes_api/node_modules
    env_file: 
      - ./.env  
    depends_on:
      - postgresDB
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:5858:5858" # V8 inspector for tools/run.js
    networks:
      - notes_network
  ####################
  # POSTGRES
  ####################
  postgresDB:
    image: postgres
    restart: always
    container_name: notes_postgresDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: notesDev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "127.0.0.1:5432:5432" # you can override it via docker-compose.override.yml
    networks:
      - notes_network

networks:
  notes_network:

volumes:
  notes_data:
  postgres_data:
  nginx_data:
